require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NoveltiesController do

  # This should return the minimal set of attributes required to create a valid
  # Novelty. As you add validations to Novelty, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NoveltiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all novelties as @novelties" do
      novelty = Novelty.create! valid_attributes
      get :index, {}, valid_session
      assigns(:novelties).should eq([novelty])
    end
  end

  describe "GET show" do
    it "assigns the requested novelty as @novelty" do
      novelty = Novelty.create! valid_attributes
      get :show, {:id => novelty.to_param}, valid_session
      assigns(:novelty).should eq(novelty)
    end
  end

  describe "GET new" do
    it "assigns a new novelty as @novelty" do
      get :new, {}, valid_session
      assigns(:novelty).should be_a_new(Novelty)
    end
  end

  describe "GET edit" do
    it "assigns the requested novelty as @novelty" do
      novelty = Novelty.create! valid_attributes
      get :edit, {:id => novelty.to_param}, valid_session
      assigns(:novelty).should eq(novelty)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Novelty" do
        expect {
          post :create, {:novelty => valid_attributes}, valid_session
        }.to change(Novelty, :count).by(1)
      end

      it "assigns a newly created novelty as @novelty" do
        post :create, {:novelty => valid_attributes}, valid_session
        assigns(:novelty).should be_a(Novelty)
        assigns(:novelty).should be_persisted
      end

      it "redirects to the created novelty" do
        post :create, {:novelty => valid_attributes}, valid_session
        response.should redirect_to(Novelty.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved novelty as @novelty" do
        # Trigger the behavior that occurs when invalid params are submitted
        Novelty.any_instance.stub(:save).and_return(false)
        post :create, {:novelty => { "title" => "invalid value" }}, valid_session
        assigns(:novelty).should be_a_new(Novelty)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Novelty.any_instance.stub(:save).and_return(false)
        post :create, {:novelty => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested novelty" do
        novelty = Novelty.create! valid_attributes
        # Assuming there are no other novelties in the database, this
        # specifies that the Novelty created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Novelty.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => novelty.to_param, :novelty => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested novelty as @novelty" do
        novelty = Novelty.create! valid_attributes
        put :update, {:id => novelty.to_param, :novelty => valid_attributes}, valid_session
        assigns(:novelty).should eq(novelty)
      end

      it "redirects to the novelty" do
        novelty = Novelty.create! valid_attributes
        put :update, {:id => novelty.to_param, :novelty => valid_attributes}, valid_session
        response.should redirect_to(novelty)
      end
    end

    describe "with invalid params" do
      it "assigns the novelty as @novelty" do
        novelty = Novelty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Novelty.any_instance.stub(:save).and_return(false)
        put :update, {:id => novelty.to_param, :novelty => { "title" => "invalid value" }}, valid_session
        assigns(:novelty).should eq(novelty)
      end

      it "re-renders the 'edit' template" do
        novelty = Novelty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Novelty.any_instance.stub(:save).and_return(false)
        put :update, {:id => novelty.to_param, :novelty => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested novelty" do
      novelty = Novelty.create! valid_attributes
      expect {
        delete :destroy, {:id => novelty.to_param}, valid_session
      }.to change(Novelty, :count).by(-1)
    end

    it "redirects to the novelties list" do
      novelty = Novelty.create! valid_attributes
      delete :destroy, {:id => novelty.to_param}, valid_session
      response.should redirect_to(novelties_url)
    end
  end

end
